version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - yum install -y git jq
      # Install OpenTofu
      - |
        echo "Installing OpenTofu version ${OPENTOFU_VERSION}"
        curl -L https://github.com/opentofu/opentofu/releases/download/v${OPENTOFU_VERSION}/tofu_${OPENTOFU_VERSION}_linux_arm64.zip -o tofu.zip
        unzip tofu.zip
        mv tofu /usr/local/bin/
        rm tofu.zip
        chmod +x /usr/local/bin/tofu
        tofu --version

  pre_build:
    commands:
      - echo "Setting up terraform plugin cache..."
      - export TF_PLUGIN_CACHE_DIR="$HOME/.terraform.d/plugin-cache"
      - mkdir -p $TF_PLUGIN_CACHE_DIR
      - echo "Loading sensitive parameters from SSM..."
      - |
        if [ ! -z "$PARAMETER_STORE_PREFIX" ]; then
          # Get all parameters and export as TF_VAR_ environment variables
          # Export them to a file first to avoid subshell issues
          aws ssm get-parameters-by-path \
            --path "$PARAMETER_STORE_PREFIX" \
            --recursive \
            --with-decryption \
            --query 'Parameters[*].[Name,Value]' \
            --output text > /tmp/ssm_params.txt
          
          # Create env file even if empty to avoid source error
          touch /tmp/env_vars.sh
          
          # Now source them in the main shell
          while IFS=$'\t' read -r name value; do
            var_name=$(echo $name | sed "s|$PARAMETER_STORE_PREFIX/||" | sed 's/^/TF_VAR_/')
            export "$var_name=$value"
            echo "export $var_name='$value'" >> /tmp/env_vars.sh
            echo "Loaded parameter: $var_name"
          done < /tmp/ssm_params.txt
          
          # Source the environment variables file
          source /tmp/env_vars.sh
        fi
      
      # Extract metadata from the source artifact
      - |
        if [ -f metadata.json ]; then
          echo "Found metadata.json:"
          cat metadata.json
          export COMMIT_SHA=$(jq -r '.commit_sha' metadata.json)
          export BRANCH=$(jq -r '.branch' metadata.json)
          export AUTHOR=$(jq -r '.author' metadata.json)
        fi

  build:
    commands:
      - echo "Running terraform plan for environment ${CODEBUILD_WEBHOOK_HEAD_REF:-$ENVIRONMENT}..."
      
      # Source the environment variables if they exist
      - |
        if [ -f /tmp/env_vars.sh ]; then
          echo "Sourcing environment variables..."
          source /tmp/env_vars.sh
        fi
      
      # Navigate to the root module directory and run terraform init
      - |
        cd $ROOT_MODULE_DIR
        echo "Running tofu init in $ROOT_MODULE_DIR..."
        tofu init -input=false
      
      # Run terraform plan
      - |
        echo "Running tofu plan..."
        echo "---------------------------------------"
        echo "---------------------------------------"
        echo "---------------------------------------"
        echo "-------------Begin Plan----------------"
        echo "---------------------------------------"
        if tofu plan -input=false -out=tfplan; then
          echo "Terraform plan succeeded"
          # Show the plan for human readability
          echo "Terraform plan output:"
          tofu show -no-color tfplan | tee plan_output.txt
          echo "SUCCESS" > build_status.txt
        else
          echo "Terraform plan failed"
          echo "FAILED" > build_status.txt
          echo "Terraform plan failed" > plan_output.txt
          exit 1
        fi
        echo "---------------------------------------"
        echo "--------------End Plan-----------------"
        echo "---------------------------------------"
        echo "---------------------------------------"
        echo "---------------------------------------"

  post_build:
    commands:
      - |
        echo "Creating summary..."
        BUILD_SUCCESS="true"
        if [ -f "build_status.txt" ] && [ "$(cat build_status.txt)" = "FAILED" ]; then
          BUILD_SUCCESS="false"
        fi
        
        # Extract resource change counts from terraform plan
        if [ -f "tfplan" ] && [ "$BUILD_SUCCESS" = "true" ]; then
          tofu show -json tfplan | jq -r '
            .resource_changes
            | map(select(.change.actions != ["no-op"]))
            | group_by(.change.actions[0])
            | map({(.[0].change.actions[0]): length})
            | add // {}
          ' > counts.json
        else
          echo '{}' > counts.json
        fi
        
        # Create summary with counts
        jq -n --argjson counts "$(cat counts.json)" \
              --arg env "$ENVIRONMENT" \
              --arg commit_sha "${COMMIT_SHA:-unknown}" \
              --arg branch "${BRANCH:-unknown}" \
              --arg author "${AUTHOR:-unknown}" \
              --argjson success $BUILD_SUCCESS \
              --arg build_id "$CODEBUILD_BUILD_ID" \
              --arg plan_output "$(cat plan_output.txt 2>/dev/null || echo "No plan output")" \
              '{
                env: $env,
                commit_sha: $commit_sha,
                branch: $branch,
                author: $author,
                success: $success,
                build_id: $build_id,
                create: ($counts.create // 0),
                update: ($counts.update // 0),
                delete: ($counts.delete // 0),
                plan_output: $plan_output
              }' > summary.json
      
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
  name: plan-output
